package provider

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/resnickio/unifi-go-sdk/pkg/unifi"
)

var (
	_ resource.Resource                = &SettingMagicSiteToSiteVPNResource{}
	_ resource.ResourceWithImportState = &SettingMagicSiteToSiteVPNResource{}
)

type SettingMagicSiteToSiteVPNResource struct {
	client *AutoLoginClient
}

type SettingMagicSiteToSiteVPNResourceModel struct {
	ID          types.String   `tfsdk:"id"`
	SiteID      types.String   `tfsdk:"site_id"`
	Enabled     types.Bool     `tfsdk:"enabled"`
	PublicKey   types.String   `tfsdk:"public_key"`
	XPrivateKey types.String   `tfsdk:"x_private_key"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}

func NewSettingMagicSiteToSiteVPNResource() resource.Resource {
	return &SettingMagicSiteToSiteVPNResource{}
}

func (r *SettingMagicSiteToSiteVPNResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_setting_magic_site_to_site_vpn"
}

func (r *SettingMagicSiteToSiteVPNResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages UniFi Magic Site-to-Site VPN settings. " +
			"This is a singleton resource — one per site. Delete resets to defaults.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"site_id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enabled": schema.BoolAttribute{
				Description: "Enable Magic Site-to-Site VPN.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"public_key": schema.StringAttribute{
				Description: "WireGuard public key (read-only, generated by the controller).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"x_private_key": schema.StringAttribute{
				Description: "WireGuard private key (write-only).",
				Optional:    true,
				Sensitive:   true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

func (r *SettingMagicSiteToSiteVPNResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*AutoLoginClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AutoLoginClient, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *SettingMagicSiteToSiteVPNResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan SettingMagicSiteToSiteVPNResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := plan.Timeouts.Create(ctx, 5*time.Minute)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	setting := r.planToSDK(&plan)
	savedPrivateKey := plan.XPrivateKey

	updated, err := r.client.UpdateSettingMagicSiteToSiteVPN(ctx, setting)
	if err != nil {
		handleSDKError(&resp.Diagnostics, err, "create", "magic site-to-site VPN setting")
		return
	}

	resp.Diagnostics.Append(r.sdkToState(updated, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.XPrivateKey = savedPrivateKey

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SettingMagicSiteToSiteVPNResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SettingMagicSiteToSiteVPNResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := state.Timeouts.Read(ctx, 2*time.Minute)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	savedPrivateKey := state.XPrivateKey

	setting, err := r.client.GetSettingMagicSiteToSiteVPN(ctx)
	if err != nil {
		handleSDKError(&resp.Diagnostics, err, "read", "magic site-to-site VPN setting")
		return
	}

	resp.Diagnostics.Append(r.sdkToState(setting, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if state.XPrivateKey.IsNull() || state.XPrivateKey.ValueString() == "" {
		state.XPrivateKey = savedPrivateKey
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *SettingMagicSiteToSiteVPNResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan SettingMagicSiteToSiteVPNResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := plan.Timeouts.Update(ctx, 5*time.Minute)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	setting := r.planToSDK(&plan)
	if !plan.ID.IsNull() {
		setting.ID = plan.ID.ValueString()
	}

	savedPrivateKey := plan.XPrivateKey

	updated, err := r.client.UpdateSettingMagicSiteToSiteVPN(ctx, setting)
	if err != nil {
		handleSDKError(&resp.Diagnostics, err, "update", "magic site-to-site VPN setting")
		return
	}

	resp.Diagnostics.Append(r.sdkToState(updated, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.XPrivateKey = savedPrivateKey

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SettingMagicSiteToSiteVPNResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state SettingMagicSiteToSiteVPNResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := state.Timeouts.Delete(ctx, 5*time.Minute)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	defaults := &unifi.SettingMagicSiteToSiteVPN{
		Key:     "magic_site_to_site_vpn",
		Enabled: boolPtr(false),
	}
	if !state.ID.IsNull() {
		defaults.ID = state.ID.ValueString()
	}

	_, err := r.client.UpdateSettingMagicSiteToSiteVPN(ctx, defaults)
	if err != nil {
		handleSDKError(&resp.Diagnostics, err, "reset", "magic site-to-site VPN setting")
		return
	}
}

func (r *SettingMagicSiteToSiteVPNResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func (r *SettingMagicSiteToSiteVPNResource) planToSDK(plan *SettingMagicSiteToSiteVPNResourceModel) *unifi.SettingMagicSiteToSiteVPN {
	s := &unifi.SettingMagicSiteToSiteVPN{
		Key:     "magic_site_to_site_vpn",
		Enabled: boolPtr(plan.Enabled.ValueBool()),
	}

	if !plan.XPrivateKey.IsNull() && !plan.XPrivateKey.IsUnknown() {
		s.XPrivateKey = plan.XPrivateKey.ValueString()
	}

	return s
}

func (r *SettingMagicSiteToSiteVPNResource) sdkToState(setting *unifi.SettingMagicSiteToSiteVPN, state *SettingMagicSiteToSiteVPNResourceModel) diag.Diagnostics {
	var diags diag.Diagnostics

	state.ID = types.StringValue(setting.ID)
	state.SiteID = types.StringValue(setting.SiteID)
	state.Enabled = types.BoolValue(derefBool(setting.Enabled))
	state.PublicKey = stringValueOrNull(setting.PublicKey)

	return diags
}
